version: "3.8"
services:
  postgres:
    image: postgres:16
    command: postgres -c "max_connections=10000"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - $HOME/projects/vector_search/all_pg_data/usual_pg:/var/lib/postgresql/data
    networks:
      - vector_search_network
    ports:
      - ${POSTGRES_PORT_TO_LOCAL_HOST}:5432

  postgres_vectors:
    image: pgvector/pgvector:pg16
    command: postgres -c "max_connections=10000"
    restart: no
    volumes:
      - $HOME/projects/vector_search/all_pg_data/vectors_pg:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5209:5432"
    networks:
      - vector_search_network

  redis:
    image: redis:latest
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - $HOME/projects/vector_search/redis:/data
    restart: unless-stopped
    networks:
      - vector_search_network

  postgres_web:
    restart: unless-stopped
    image: sosedoff/pgweb
    env_file:
      - .env
    ports:
      - "8083:8081"
    links:
      - postgres:postgres  # my database container is called postgres, not db
    environment:
      - PGWEB_DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    depends_on:
      - postgres # my database container is called postgres, not db
    networks:
      - vector_search_network
  postgres_web_vectors:
    restart: unless-stopped
    image: sosedoff/pgweb
    env_file:
      - .env
    ports:
      - "8084:8081"
    environment:
      - PGWEB_DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_vectors:5432/${POSTGRES_DB}?sslmode=disable
    depends_on:
      - postgres_vectors # my database container is called postgres, not db
    networks:
      - vector_search_network

  vector_search_app:
    build: .
    restart: unless-stopped
    container_name: "vector_search"
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8787"
    volumes:
      - /home/izbushko/projects/vector_search/vector_search/logs:/app/logs
    networks:
      - vector_search_network
    depends_on:
      - postgres
      - postgres_vectors

networks:
  vector_search_network:
    external: false
